[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustls = "0.22.1"
x509-parser = "0.15.1"
proto = { path = "../proto", features = ["rust-tls"]}
